version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
      - 4001-4041:4040
      - 5001-5051:5050
    volumes:
      - ./app/allure/allure-results:/app/allure-results
    networks:
      - webnet
networks:
  webnet:
